// Photos matériaux — patch (v2 : fichiers hébergés, plus de base64)
// Les images vivent dans le dossier /photos/materiaux/ du repo, à côté de app.html
if(typeof PHOTOS_DB !== "undefined") {
  PHOTOS_DB["enrobesBitumineux"] = ["photos/materiaux/enrobesBitumineux-1.jpg", "photos/realisations/enrobes-bitumineux-1.jpeg", "photos/realisations/enrobes-bitumineux-2.jpg", "photos/realisations/enrobes-bitumineux-3.jpeg", "photos/realisations/enrobes-bitumineux-4.jpeg"];
  PHOTOS_DB["pavageDallage"] = ["photos/materiaux/pavageDallage-1.jpg", "photos/materiaux/pavageDallage-2.jpg", "photos/materiaux/pavageDallage-3.jpeg", "photos/materiaux/pavageDallage-4.jpeg", "photos/materiaux/pavageDallage-5.jpeg", "photos/materiaux/pavageDallage-6.jpeg", "photos/materiaux/pavageDallage-7.jpeg", "photos/materiaux/pavageDallage-8.jpeg", "photos/materiaux/pavageDallage-9.jpeg"];
  PHOTOS_DB["resineMarbre"] = ["photos/materiaux/resineMarbre-1.jpg", "photos/materiaux/resineMarbre-2.jpeg", "photos/materiaux/resineMarbre-3.jpeg", "photos/materiaux/resineMarbre-4.jpeg", "photos/materiaux/resineMarbre-5.jpeg", "photos/materiaux/resineMarbre-6.jpeg", "photos/materiaux/resineMarbre-7.jpeg", "photos/materiaux/resineMarbre-8.jpeg", "photos/materiaux/resineMarbre-9.jpeg", "photos/materiaux/resineMarbre-10.jpeg", "photos/materiaux/resineMarbre-11.jpeg"];
  PHOTOS_DB["gravierBicouche"] = ["photos/materiaux/gravierBicouche-1.jpg"];
  PHOTOS_DB["gravierStabilise"] = ["photos/materiaux/gravierStabilise-1.jpg", "photos/materiaux/gravierStabilise-2.jpg", "photos/materiaux/gravierStabilise-3.jpg"];
  PHOTOS_DB["terrassteel"] = ["photos/materiaux/terrassteel-1.jpg", "photos/materiaux/terrassteel-2.jpeg", "photos/materiaux/terrassteel-3.jpeg", "photos/materiaux/terrassteel-4.jpeg", "photos/materiaux/terrassteel-5.jpeg", "photos/materiaux/terrassteel-6.jpeg", "photos/materiaux/terrassteel-7.jpeg", "photos/materiaux/terrassteel-8.jpeg", "photos/materiaux/terrassteel-9.jpeg", "photos/materiaux/terrassteel-10.jpeg", "photos/materiaux/terrassteel-11.jpeg", "photos/materiaux/terrassteel-12.jpeg", "photos/materiaux/terrassteel-13.jpeg", "photos/materiaux/terrassteel-14.jpeg", "photos/materiaux/terrassteel-15.jpeg", "photos/materiaux/terrassteel-16.jpeg", "photos/materiaux/terrassteel-17.jpeg", "photos/materiaux/terrassteel-18.jpeg", "photos/materiaux/terrassteel-19.jpeg", "photos/materiaux/terrassteel-20.jpeg", "photos/materiaux/terrassteel-21.jpeg"];
  PHOTOS_DB["pierreNaturelle"] = ["photos/materiaux/pierreNaturelle-1.jpg", "photos/materiaux/pierreNaturelle-2.jpeg", "photos/materiaux/pierreNaturelle-3.jpeg", "photos/materiaux/pierreNaturelle-4.jpeg", "photos/materiaux/pierreNaturelle-5.jpeg", "photos/materiaux/pierreNaturelle-6.jpeg", "photos/materiaux/pierreNaturelle-7.jpeg", "photos/materiaux/pierreNaturelle-8.jpeg"];
  PHOTOS_DB["terrassePavage"] = ["photos/materiaux/terrassePavage-1.jpg", "photos/materiaux/terrassePavage-2.jpeg", "photos/materiaux/terrassePavage-3.jpeg", "photos/materiaux/terrassePavage-4.jpeg", "photos/materiaux/terrassePavage-5.jpeg"];
  PHOTOS_DB["clotureLamesBois"] = ["photos/materiaux/clotureLamesBois-1.jpg"];
  PHOTOS_DB["claireVoieBois"] = ["photos/materiaux/claireVoieBois-1.jpg"];
  PHOTOS_DB["compositeTraumgarten"] = ["photos/materiaux/compositeTraumgarten-1.jpg", "photos/materiaux/compositeTraumgarten-2.jpeg", "photos/materiaux/compositeTraumgarten-3.jpeg", "photos/materiaux/compositeTraumgarten-4.jpeg", "photos/materiaux/compositeTraumgarten-5.jpeg", "photos/materiaux/compositeTraumgarten-6.jpeg", "photos/materiaux/compositeTraumgarten-7.jpeg", "photos/materiaux/compositeTraumgarten-8.jpeg", "photos/materiaux/compositeTraumgarten-9.jpeg"];
  PHOTOS_DB["boisPinTerrasse"] = ["photos/materiaux/boisPinTerrasse-1.jpg", "photos/materiaux/boisPinTerrasse-2.jpeg", "photos/materiaux/boisPinTerrasse-3.jpeg", "photos/materiaux/boisPinTerrasse-4.jpeg", "photos/materiaux/boisPinTerrasse-5.jpeg", "photos/materiaux/boisPinTerrasse-6.jpeg", "photos/materiaux/boisPinTerrasse-7.jpeg", "photos/materiaux/boisPinTerrasse-8.jpeg", "photos/materiaux/boisPinTerrasse-9.jpeg", "photos/materiaux/boisPinTerrasse-10.jpeg", "photos/materiaux/boisPinTerrasse-11.jpeg", "photos/materiaux/boisPinTerrasse-12.jpeg", "photos/materiaux/boisPinTerrasse-13.jpeg", "photos/materiaux/boisPinTerrasse-14.jpeg", "photos/materiaux/boisPinTerrasse-15.jpeg", "photos/materiaux/boisPinTerrasse-16.jpeg"];
  PHOTOS_DB["panneauxRigidesMRT"] = ["photos/materiaux/panneauxRigidesMRT-1.jpg", "photos/materiaux/panneauxRigidesMRT-2.jpg", "photos/materiaux/panneauxRigidesMRT-3.jpg", "photos/materiaux/panneauxRigidesMRT-4.jpg", "photos/materiaux/panneauxRigidesMRT-5.jpg"];
  PHOTOS_DB["pergolaAluminium"] = ["photos/materiaux/pergola-aluminium-1.jpeg", "photos/materiaux/pergola-aluminium-2.jpeg", "photos/materiaux/pergola-aluminium-3.jpeg"];
  PHOTOS_DB["storeVelumPergola"] = ["photos/materiaux/store-velum-pergola-1.jpeg", "photos/materiaux/store-velum-pergola-2.jpeg"];
}
